### ISSUE TITLE
Bug: Text blurs when module enabled

### ISSUE THREAD

**Issue by paddy74** [ruipin/fvtt-better-text-drawings#1]
When this module is enabled, drawn text is blurry. This occurs with or without libWrapper enabled. This effectively makes the module unusable.

Blurry text:
![Capture](https://user-images.githubusercontent.com/14883939/96490975-97788700-120f-11eb-9c22-5d1bc35925fc.PNG)

Expected
![Capture](https://user-images.githubusercontent.com/14883939/96491089-becf5400-120f-11eb-836b-bfac1112679a.PNG)

**Comment by ruipin** [comment]
The module still hasn't been updated for 1.7.x, which I believe is when the blurriness of the text was fixed in Foundry. I suspect you're just seeing the module "undo" the fixes introduced by 1.7.x.

**Comment by ruipin** [comment]
This is now fixed in [v1.0.3](https://github.com/ruipin/fvtt-better-text-drawings/releases/tag/v1.0.3), which is the first release to officially support Foundry 0.7.5.
