### ISSUE TITLE
button in journal header

### ISSUE THREAD

**Issue by Darshyne** [ruipin/fvtt-better-text-drawings#2]
Hello, would it be possible to have a shorten button in journal windows? Maybe only the play button, because the "play as transition" is very long and is often pressed by mistake.
Anyway thank you for this awesome module.

**Comment by ruipin** [comment]
Unless I'm misunderstanding something, did you mistakenly open this in the wrong repository?
"Better Text Drawings" has nothing to do with the journal or a "Play as Transition" button.

**Comment by ruipin** [comment]
Closing as this has nothing to do with this module.
