### ISSUE TITLE
How do you choose text alignment?

### ISSUE THREAD

**Issue by weihanderz** [ruipin/fvtt-better-text-drawings#3]
I can't seem to find the text alignment settings.

**Comment by ruipin** [comment]
![image](https://user-images.githubusercontent.com/11169970/103886975-3c518480-50da-11eb-8417-1f3ee7ae21fd.png)

**Comment by IndigoGnat** [comment]
The Text Alignment dropdown is not showing up for me even when this is and LibWrapper are the only active modules
