### ISSUE TITLE
Stroke option gone

### ISSUE THREAD

**Issue by tanzilhassan1306** [ruipin/fvtt-better-text-drawings#8]
The text stroke option is no longer present after the latest update, as can be seen below.

![image](https://user-images.githubusercontent.com/49132181/125152165-dc837700-e118-11eb-9294-ea68fa10bab3.png)

**Comment by ruipin** [comment]
Thanks for the report, I was surprised for a second as it worked for me, but then noticed that with the v1.1.0.0 updates I accidentally broke the release workflow, and it stopped including the `*.js` files with the release artifacts, effectively making the module do nothing.

[v1.1.0.1](https://github.com/ruipin/fvtt-better-text-drawings/releases/tag/v1.1.0.1) fixes this. Sorry about that.

Closing this issue as resolved. Feel free to re-open if you still see issues after updating.

**Comment by tanzilh** [comment]
No worries at all, thank you for the swift fix on this fantastic module. Keep up the great work!
